# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/configuration/wrangler-configuration/

name = "tiptap-block-designer"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "pnpm run build"
